# Generated by Django 3.2 on 2021-05-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
            ],
        ),
    ]
