# Generated by Django 3.2 on 2021-05-24 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuni', '0002_newusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('lastmodifiedon', models.DateTimeField(auto_now_add=True)),
                ('lastPurchasedStore', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('additionalParam', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='elastic_index_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_code', models.CharField(blank=True, max_length=250)),
                ('group_name', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('primaryClass', models.CharField(blank=True, max_length=100)),
                ('secondaryClass', models.CharField(blank=True, max_length=100)),
                ('additionalParam', models.JSONField()),
                ('brandId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_code', to='yuni.brandcode')),
            ],
        ),
        migrations.CreateModel(
            name='fieldMappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNames', models.CharField(blank=True, max_length=250)),
                ('elasticNames', models.CharField(blank=True, max_length=250)),
                ('platformVariables', models.CharField(blank=True, max_length=100)),
                ('customerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerNames', to='yuni.customer')),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('branchName', models.CharField(blank=True, max_length=100)),
                ('lattitude', models.CharField(blank=True, max_length=100)),
                ('longitude', models.DateTimeField(auto_now_add=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('additionalParam', models.JSONField()),
                ('customerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branchName', to='yuni.customer')),
            ],
        ),
    ]
