# Generated by Django 3.2 on 2021-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuni', '0006_alter_brandcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcode',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
