# Generated by Django 3.2 on 2021-05-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuni', '0007_alter_brandcode_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='fieldmappings',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='branchId',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='brandId',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='customerId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='customerId',
            new_name='customer',
        ),
    ]
